[package]
name = "tile-prune"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "tile_prune"
path = "src/lib.rs"

[[bin]]
name = "tile-prune"
path = "src/main.rs"
